apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: sinitsynva/otus-homework
    context: sinitsynva/otus-homework
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
