apiVersion: v1
kind: ConfigMap
metadata:
  name: client-manger-config
data:
  SOME_PARAM: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: client-manager-secrets-1
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s-%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.name .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
