apiVersion: v1
kind: ConfigMap
metadata:
  name: client-manger-config
data:
  SOME_PARAM: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: client-manager-secrets
type: Opaque
data: 
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s/%s" .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlDatabase  | b64enc | quote }}
