apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}

spec:
    replicas: {{ .Values.replicaCount }}
    selector:
       matchLabels:
          app: {{ .Values.image.appname }}
    template:
       metadata:
          labels:
             app: {{ .Values.image.appname }}
#          annotations:
#        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
       spec:
          containers:
          - name: {{ .Values.image.name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            env:
              - name: DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: client-manager-secrets-1
                    key: DATABASE_URI
            ports:
              - name: web
                containerPort: 70
                protocol: TCP
            livenessProbe:
              httpGet:
                port: 70
                path: /livenessProbe
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 70
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
