apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}

spec:
  selector:
    app: {{ .Values.image.appname }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      #name: web
