replicaCount: 2

image:
  repository: sinitsynva/otus-homework
  appname: client-manger
  container:
    name: otushomework-node


service:
  name: client-manger-service
  type: NodePort
  port: 8000

deployment:
  name: client-manger-deployment

postgresql:
  enabled: true
  postgresqlUsername: otshwrkuser
  postgresqlPassword: secret
  postgresqlDatabase: OTSHWRKDB
  name: postgresql
