replicaCount: 2

image:
  repository: sinitsynva/otus-homework

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: otshwrkuser
  postgresqlPassword: secret
  postgresqlDatabase: OTSHWRKDB
  postgresqlHost: postgres
