apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-node
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-service-node
              port:
                number: 8000
