apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: sinitsynva/otus-homework
deploy:
  kubectl:
    manifests:
    - postgre.yaml
    - deployment.yaml
    - service.yaml
    - secrets.yaml
